name: Test Extract Release Note (temp)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (id) to extract from CHANGELOG (e.g., v0.2.1)'
        required: false
        default: ''

permissions: {}

jobs:
  test-extract:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      next_tag: ${{ steps.set-tag.outputs.next_tag }}
      release_note: ${{ steps.extract.outputs.release_note }}
    steps:
      - uses: actions/checkout@v5

      - name: Determine NEXT_TAG
        id: set-tag
        shell: bash
        run: |
          set -euo pipefail
          # If provided via workflow_dispatch input, use it; else take first section header from CHANGELOG
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG=$(awk '/^# \[.*\]/{gsub(/^# \[|\].*$/,""); print; exit}' CHANGELOG.md)
          fi
          echo "Detected NEXT_TAG: ${TAG}"
          echo "next_tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Install kugiri
        uses: binary-install/setup-x@v1
        with:
          script_url: https://github.com/actionutils/kugiri/releases/latest/download/install.sh
          gh_attestations_verify_flags: --repo=actionutils/kugiri --signer-workflow=actionutils/trusted-go-releaser/.github/workflows/trusted-release-workflow.yml

      - name: Extract release note
        id: extract
        env:
          NEXT_TAG: ${{ steps.set-tag.outputs.next_tag }}
        shell: bash
        run: |
          set -euo pipefail
          NOTE=$(kugiri extract --id "${NEXT_TAG}" CHANGELOG.md | kugiri trim)
          {
            echo "release_note<<EOF"
            echo "$NOTE"
            echo EOF
          } >> "$GITHUB_OUTPUT"
          {
            echo "Tag: ${NEXT_TAG}"
            echo
            echo "$NOTE"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Show preview in logs
        shell: bash
        run: |
          echo "NEXT_TAG: ${{ steps.set-tag.outputs.next_tag }}"
          echo "----- Release Note (first 20 lines) -----"
          echo "${{ steps.extract.outputs.release_note }}" | head -n 20
          echo "----------------------------------------"

